name: 'Docs or taiga-ui.dev Bug Report'
description: Report an issue in Taiga's documentation or taiga-ui.dev application

body:
    - type: textarea
      id: description
      attributes:
          label: Description
      validations:
          required: true

    - type: input
      id: affected-url
      attributes:
          label: What is the affected URL?

    - type: textarea
      id: screenshot
      attributes:
          label: Please provide a screenshot if possible

    - type: textarea
      id: browser-info
      attributes:
          label: Is this a browser-specific issue? If so, please specify the device, browser, and version.
          render: true
