name: Rebase onto main

on:
    push:
        branches: [main]

jobs:
    rebase:
        runs-on: ubuntu-latest
        steps:
            - name: Setup name for action bot
              run: git config user.name "tinkoff-bot"
            - name: Autorebase
              continue-on-error: true
              uses: peter-evans/rebase@v1.1.0
              with:
                  token: ${{ secrets.TINKOFF_BOT_PAT }}
                  base: main

concurrency:
    group: autorebase-${{ github.head_ref }}
    cancel-in-progress: true
