name: Release Taiga UI packages

on:
  push:
    branches:
      - 'release/**'

env:
  NX_BRANCH: ${{ github.event.number }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Build publishable libraries
        run: npm run run-many:build:libs

      - name: Check core is already published
        id: core-published
        run: |
          VERSION=$(node -pe "require('./package.json').version")
          echo "::set-output name=published::$(npm view @taiga-ui/core@"$VERSION" version | wc -l | sed -e 's/^[[:space:]]*//')"

      - name: Publish libraries
        if: ${{ steps.core-published.outputs.published == '0' }}
        run: npm run run-many:publish:libs

concurrency:
  group: release-${{ github.head_ref }}
  cancel-in-progress: true
