name: Unit tests

on:
    pull_request:
        paths:
            - 'projects/**'
            - '!projects/*testing/**'
            - '!projects/demo/**'
            - '!projects/icons/**'
            - '.github/workflows/test.yml'
            - 'angular.json'
            - 'package.json'
            - 'tsconfig*'
    push:
        branches:
            - main
            - '!release/**'

env:
    NX_BRANCH: ${{ github.event.number }}
    NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    NX_MAX_PARALLEL: 3

jobs:
    test:
        name: Karma
        # Setup part
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Cache Node.js modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-node-
                      ${{ runner.OS }}-
            - name: Install dependencies
              run: npm ci
            # End of setup
            - name: Run affected tests
              run: npm run task scripts/affected/affected-tests.ts
            # Coveralls part
            - name: Coveralls(cdk)
              continue-on-error: true
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: ./coverage/cdk/lcov.info
            - name: Coveralls(core)
              continue-on-error: true
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: ./coverage/core/lcov.info
            - name: Coveralls(kit)
              continue-on-error: true
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: ./coverage/kit/lcov.info
            - name: Coveralls(addon-charts)
              continue-on-error: true
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: ./coverage/addon-charts/lcov.info
            - name: Coveralls(addon-commerce)
              continue-on-error: true
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: ./coverage/addon-commerce/lcov.info
            - name: Coveralls(addon-editor)
              continue-on-error: true
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: ./coverage/addon-editor/lcov.info
            - name: Coveralls(addon-table)
              continue-on-error: true
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: ./coverage/addon-table/lcov.info
            - name: Coveralls Finished
              continue-on-error: true
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel-finished: true
            # End of Coveralls

concurrency:
    group: test-${{ github.head_ref }}
    cancel-in-progress: true
